package bbu.solution.logwatchai.domain.alert;

import bbu.solution.logwatchai.domain.analysis.Severity;
import bbu.solution.logwatchai.domain.log.LogEntry;
import bbu.solution.logwatchai.domain.logsource.LogSource;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.*;

/**
 * Represents an alert generated by the system based on rule evaluation or anomaly detection.
 * Alerts reference their originating LogSource and optionally the associated LogEntry.
 *
 * <p>This entity stores severity, message text, rule names that triggered the alert,
 * whether the alert is still active, and timestamps for creation.</p>
 *
 * <p>The alert can be activated or deactivated through domain methods.</p>
 */
@Entity
@Table(
        name = "alerts",
        indexes = {
                @Index(name = "idx_alerts_active", columnList = "active"),
                @Index(name = "idx_alerts_severity", columnList = "severity"),
                @Index(name = "idx_alerts_created_at", columnList = "created_at DESC"),
                @Index(name = "idx_alerts_source_id", columnList = "source_id")
        }
)
@Getter
@NoArgsConstructor
@AllArgsConstructor
public class Alert {

    /**
     * Unique identifier of the alert.
     */
    @Id
    @GeneratedValue
    @Column(nullable = false, columnDefinition = "BINARY(16)")
    @JdbcTypeCode(SqlTypes.BINARY)
    private UUID id;

    /**
     * Timestamp indicating when the alert was created.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt = Instant.now();

    /**
     * Severity level of the alert.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Setter
    private Severity severity;

    /**
     * Human-readable message describing the reason for the alert.
     */
    @Column(nullable = false, length = 500)
    @Setter
    private String message;

    /**
     * List of rule names (strings) that triggered this alert.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "rule_names", columnDefinition = "json", nullable = false)
    private List<String> ruleNames = new ArrayList<>();

    /**
     * Indicator whether the alert is still active.
     */
    @Column(nullable = false)
    @Setter
    private boolean active = true;

    /**
     * Reference to the ID of the originating log source.
     */
    @Column(name = "source_id", columnDefinition = "BINARY(16)")
    @JdbcTypeCode(SqlTypes.BINARY)
    @Setter
    private UUID sourceId;

    /**
     * Lazy-loaded reference to the originating LogSource.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "source_id", insertable = false, updatable = false)
    private LogSource source;

    /**
     * Optional reference to the originating LogEntry.
     */
    @Column(name = "log_entry_id", columnDefinition = "BINARY(16)")
    @JdbcTypeCode(SqlTypes.BINARY)
    @Setter
    private UUID logEntryId;

    /**
     * Lazy-loaded LogEntry associated with this alert.
     */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "log_entry_id", insertable = false, updatable = false)
    private LogEntry logEntry;

    /**
     * Builder for easier alert creation.
     * Copies ruleNames defensively and supports optional logEntryId.
     */
    @Builder
    public Alert(Severity severity, String message, List<String> ruleNames, UUID sourceId, UUID logEntryId) {
        this.severity = severity;
        this.message = message;
        this.sourceId = sourceId;
        this.ruleNames = (ruleNames == null ? new ArrayList<>() : new ArrayList<>(ruleNames));
        this.logEntryId = logEntryId;
    }

    /**
     * Marks this alert as inactive.
     */
    public void deactivate() {
        this.active = false;
    }

    /**
     * Marks this alert as active.
     */
    public void activate() {
        this.active = true;
    }

    /**
     * Replaces the stored rule names with a defensive copy of the new list.
     */
    public void setRuleNames(List<String> ruleNames) {
        this.ruleNames = (ruleNames == null)
                ? new ArrayList<>()
                : new ArrayList<>(ruleNames);
    }
}
