namespace LogWatchAiWebApp.Shared.Models.Entities
{
    /// <summary>
    /// Represents an alert generated by the backend system.
    /// Contains metadata such as severity, creation time,
    /// message, and identifiers linking to the source and log entry.
    /// </summary>
    public class Alert
    {
        /// <summary>
        /// Unique identifier of the alert.
        /// </summary>
        public string id { get; set; }

        /// <summary>
        /// Timestamp when the alert was created.
        /// </summary>
        public DateTime createdAt { get; set; }

        /// <summary>
        /// Severity level of the alert (e.g., INFO, LOW, MEDIUM, HIGH, CRITICAL).
        /// </summary>
        public string severity { get; set; }

        /// <summary>
        /// Human-readable message describing the alert.
        /// </summary>
        public string message { get; set; }

        /// <summary>
        /// Identifier of the source system that generated the alert.
        /// </summary>
        public string sourceId { get; set; }

        /// <summary>
        /// Identifier of the associated log entry.
        /// </summary>
        public string logEntryId { get; set; }
    }
}