namespace LogWatchAiWebApp.Shared.Models.Entities
{
    /// <summary>
    /// Represents a single analysis entry generated by the backend.
    /// Contains details such as severity, anomaly score, summary, 
    /// timestamp of analysis, and associated log entry ID.
    /// </summary>
    public class AnalysisEntry
    {
        /// <summary>
        /// Unique identifier of the analysis entry.
        /// </summary>
        public string id { get; set; }

        /// <summary>
        /// Timestamp when the analysis was performed.
        /// </summary>
        public DateTime analyzedAt { get; set; }

        /// <summary>
        /// Severity level of the analysis (e.g., INFO, LOW, MEDIUM, HIGH, CRITICAL).
        /// </summary>
        public string severity { get; set; }

        /// <summary>
        /// Numeric score indicating the anomaly level detected.
        /// </summary>
        public double anomalyScore { get; set; }

        /// <summary>
        /// Summarized issue description from the analysis.
        /// </summary>
        public string summarizedIssue { get; set; }

        /// <summary>
        /// Identifier of the log entry associated with this analysis.
        /// </summary>
        public string logEntryId { get; set; }
    }
}