using System.Text.Json.Serialization;

namespace LogWatchAiWebApp.Shared.Models
{
    /// <summary>
    /// Represents an alert generated by the LogWatchAI backend.
    /// Contains metadata such as severity, creation timestamp, message details,
    /// and identifiers linking the alert to its source and log entry.
    /// </summary>
    public class AlertDto
    {
        /// <summary>
        /// Unique identifier of the alert.
        /// </summary>
        [JsonPropertyName("id")]
        public string? Id { get; set; }

        /// <summary>
        /// Timestamp when the alert was created.
        /// </summary>
        [JsonPropertyName("createdAt")]
        public DateTimeOffset? CreatedAt { get; set; }

        /// <summary>
        /// Severity level of the alert (e.g., INFO, LOW, MEDIUM, HIGH, CRITICAL).
        /// </summary>
        [JsonPropertyName("severity")]
        public string? Severity { get; set; }

        /// <summary>
        /// Human-readable message describing why the alert was triggered.
        /// </summary>
        [JsonPropertyName("message")]
        public string? Message { get; set; }

        /// <summary>
        /// List of rule names that triggered the alert.
        /// </summary>
        [JsonPropertyName("ruleNames")]
        public List<string>? RuleNames { get; set; }

        /// <summary>
        /// Indicates whether the alert is currently active.
        /// </summary>
        [JsonPropertyName("active")]
        public bool? Active { get; set; }

        /// <summary>
        /// Identifier of the source system that produced the alert.
        /// </summary>
        [JsonPropertyName("sourceId")]
        public string? SourceId { get; set; }

        /// <summary>
        /// Identifier of the log entry associated with the alert.
        /// </summary>
        [JsonPropertyName("logEntryId")]
        public string? LogEntryId { get; set; }
    }
}